name: C++ Tests

on:
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      - name: Build UI
        run: |
          cd UI
          make all

      - name: Run sorting unit tests
        run: |
          cd UI
          make test
